import type { ThemePalette } from '../types';

// Ported from ui/theme/colors/PurpleThemeColors.kt. This is the app's default palette.
export const purple: ThemePalette = {
  light: {
    primary: '#5F00D6',
    onPrimary: '#FFFFFF',
    primaryContainer: '#7A28FE',
    onPrimaryContainer: '#EADCFF',
    secondary: '#6B4BAE',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#B594FD',
    onSecondaryContainer: '#472489',
    tertiary: '#8F007E',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#B800A3',
    onTertiaryContainer: '#FFD7F0',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    background: '#FEF7FF',
    onBackground: '#1D1A25',
    surface: '#FEF7FF',
    onSurface: '#1D1A25',
    surfaceVariant: '#E9DEF6',
    onSurfaceVariant: '#4A4456',
    scrim: '#000000',
    inverseSurface: '#332E3A',
    inverseOnSurface: '#F6EDFE',
    inversePrimary: '#D2BCFF',
    border: '#D2BCFF',
  },
  dark: {
    primary: '#D2BCFF',
    onPrimary: '#3D008F',
    primaryContainer: '#7A28FE',
    onPrimaryContainer: '#EADCFF',
    secondary: '#D2BCFF',
    onSecondary: '#3B167D',
    secondaryContainer: '#48415B',
    onSecondaryContainer: '#DFD3F8',
    tertiary: '#A071F8',
    onTertiary: '#5E0052',
    tertiaryContainer: '#B800A3',
    onTertiaryContainer: '#FFD7F0',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    background: '#15121C',
    onBackground: '#E8DFF0',
    surface: '#15121C',
    onSurface: '#E8DFF0',
    surfaceVariant: '#4A4456',
    onSurfaceVariant: '#CCC3D9',
    scrim: '#000000',
    inverseSurface: '#E8DFF0',
    inverseOnSurface: '#332E3A',
    inversePrimary: '#741BF8',
    border: 'rgba(116, 27, 248, 0.75)',
  },
};
