import type { ThemePalette } from '../types';

// Ported from ui/theme/colors/RedThemeColors.kt.
export const red: ThemePalette = {
  light: {
    primary: '#904A42',
    onPrimary: '#FFFFFF',
    primaryContainer: '#FFDAD5',
    onPrimaryContainer: '#73342C',
    secondary: '#775652',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#FFDAD5',
    onSecondaryContainer: '#5D3F3B',
    tertiary: '#715C2E',
    onTertiary: '#FFFFFF',
    tertiaryContainer: '#FDDFA6',
    onTertiaryContainer: '#574419',
    error: '#BA1A1A',
    onError: '#FFFFFF',
    errorContainer: '#FFDAD6',
    onErrorContainer: '#93000A',
    background: '#FFF8F7',
    onBackground: '#231918',
    surface: '#FFF8F7',
    onSurface: '#231918',
    surfaceVariant: '#F5DDDA',
    onSurfaceVariant: '#534341',
    scrim: '#000000',
    inverseSurface: '#392E2C',
    inverseOnSurface: '#FFEDEA',
    inversePrimary: '#FFB4AA',
    border: '#FFB4AA',
  },
  dark: {
    primary: '#FFB4AA',
    onPrimary: '#561E18',
    primaryContainer: '#73342C',
    onPrimaryContainer: '#FFDAD5',
    secondary: '#E7BDB7',
    onSecondary: '#442926',
    secondaryContainer: '#5D3F3B',
    onSecondaryContainer: '#FFDAD5',
    tertiary: '#DFC38C',
    onTertiary: '#3F2E04',
    tertiaryContainer: '#574419',
    onTertiaryContainer: '#FDDFA6',
    error: '#FFB4AB',
    onError: '#690005',
    errorContainer: '#93000A',
    onErrorContainer: '#FFDAD6',
    background: '#1A1110',
    onBackground: '#F1DEDC',
    surface: '#1A1110',
    onSurface: '#F1DEDC',
    surfaceVariant: '#534341',
    onSurfaceVariant: '#D8C2BE',
    scrim: '#000000',
    inverseSurface: '#F1DEDC',
    inverseOnSurface: '#392E2C',
    inversePrimary: '#C0000C',
    border: '#C0000C',
  },
};
